export const products = [
  {
    id: 1,
    name: "Crimson Heritage Tant",
    category: "Tant Cotton",
    subcategory: "Lightweight | Daily Wear",
    price: 1200,
    badge: "Best Seller",
    badgeStyle: "bg-white/90 backdrop-blur-sm text-secondary",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB0SoUzqbISdAfwWKi1GzZGL9DvK4ucRAUQPrSmx_Lp57hn4H3MMNhjvAQCuSmU7D_ngINJZ-cMxV6hEr2068ekYnS1L4PSv98OR38qZwJaODRRMobrkrHtual6IIsUAZvkIsnre1MN2lpTPTO93xrYj-_KPp34TSEK8iVl74AQ-pWECpBK0iKVWYosaQzV-7ENimkcZ8RkeSMcUj5CgaX4KylCK3nY8vSc_48yMpFW3uOgYY3nEC1VCBu4l-a6cDA5qyJqpIm_Ra4z",
    alt: "Elegant red handwoven Tant saree with intricate gold zari borders",
    offset: false,
  },
  {
    id: 2,
    name: "Royal Murshidabad Silk",
    category: "Pure Silk",
    subcategory: "Formal | Evening Wear",
    price: 8500,
    badge: "Premium Silk",
    badgeStyle: "bg-primary text-white",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAvKNJM-uybFMJ3L7HA14Luyi_nT39TfepPl_FP1CjsfBIhGpJhJ86kM8GBIIM50W6vyAEmbUsfcKeIRh89Jb-s568UTr9wDQsA5Q9yedG_f93UAle3Ch536tfNJb8OISVSEIxAIwwLqvi_pDoOfU5q6g5qkAI8DJK9kuVAlzRFNlSwK2p5T8GjVli6WjF6Ffp8KYJGr8cLjqOmlN38d2AcdeADZZzN2SzZWFs9o1DX1ioj7nY-wTnQLljuSvL0xv89eMMdgRyE4scx",
    alt: "Exquisite royal blue Murshidabad silk saree with silver motifs",
    offset: true,
  },
  {
    id: 3,
    name: "Dhaka Jamdani White",
    category: "Jamdani Heritage",
    subcategory: "Artisan Crafted | Handloom",
    price: 14200,
    badge: null,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCmo5WTJBJi0BDjm2zMEmEYz_MaB8qa-orBdhsJcZnElc-KlY9QfJQZH0t2bZI9FEmVlZdFfyCUejtTslSfR7yvVWryr5-dqHOiy2Nki14CivNBl7APbWRRUgCPL335sTps-1sqKCismExCyGa26wx0sO8foPTPBAdtp_v-1lM8Bn6MZuU_wcqYbDGXe83PTy9W-a6Pgrh2B5P1Q-4_ZWpXIUvNEgpdYQjbdyPSdTExBrYl9LuHYSIcpll15F7pgQgwZfSoSJln0Ugf",
    alt: "White and gold Bengali Jamdani saree with floral muslin weaves",
    offset: false,
  },
  {
    id: 4,
    name: "Golden Tussar Block Print",
    category: "Baluchari",
    subcategory: "Raw Texture | Office Wear",
    price: 4800,
    badge: null,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBP86GVBKn4v_yuK5CiSDdKWAB0J0cX7g4HrzB-GkKNHgUdGgk3Hr8VRWCo6DmeT-9iMECXwFkAxnHLwEG7fwafEUi-GbPt5NgE9fIpt4fjEhcVrm7KoIHBAjMnPUrooQNVxI0aCLvTcDdsutqR6tnSZiwzn3lLUnsX1Q7V-QKNziVeSOZx-vXlQJ6uob8SSFzvSCnwfpHCn7TlZGug_45G1RFMphfRbOzNRuJjpGc2CHK4jfg0Ya_bj4uJpHH2fexqH4I2l52kDUs9",
    alt: "Deep yellow Tussar silk saree with brown earthy block prints",
    offset: false,
  },
  {
    id: 5,
    name: "Classic Garad Silk",
    category: "Pure Silk",
    subcategory: "Festive | Puja Special",
    price: 6200,
    badge: null,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDoiZoa8EkQx6F1RaDxvd5wIebiusVj69DG9wakn4j_VihPj-cCIkV0GGj7Pi4xPfYTFWKstA3Kph9wkUxzOfT-kXmkS1hDE6hOY6rC7JyET6GF7i7jeoTw6ILPubDMUjZh6oAse1KXWymmhi_NZwW7ehrGIxHZPYnnUQXeRheBamUi_T5DkNNBSs8yoM2fixmwnpcByPuNOYsb8n1d-wzYcoX_ReL4BC_gSyGRZcYxTNK1wKUhwN77aGtOdFyXMl5y4vKLng0xCEjz",
    alt: "Classic red and white Garad saree in traditional Bengali style",
    offset: true,
  },
  {
    id: 6,
    name: "Emerald Floral Benarasi",
    category: "Pure Silk",
    subcategory: "Luxury | Wedding Wear",
    price: 18000,
    badge: null,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCK6dJMmAtOAbqhd9uyKRAKnVP2NGtjLSjuIK2pNT_tx4bGQaFN2l64t0OGAMeCnAGkulKP2Nj-4UryPfDm0v7vfniZVP-troZjCpIfUaIqrORo48ieRAId-u3XSk5Znqeh20ydo5PNQFFjA9JCXekeVd8Q0nRMelxnsoX2lgEQCeotP4nvWQkHxjVx5C7xbjM2UydyofzgW2VQsvLeWqeg7Od4jopV8KmXWVW9RaLhmM1T1ZczRZVFp-ezNw-A6s2j0083FrIvzAAf",
    alt: "Emerald green soft silk saree with floral vine motifs in silver",
    offset: false,
  },
];

export const featuredProduct = {
  id: 1,
  name: "Handwoven Blue Jamdani",
  price: "₹ 24,500",
  category: "Jamdani",
  description:
    "Woven in the heart of West Bengal, this Jamdani represents a lineage of craftsmanship. Each floral motif is hand-threaded onto the loom, creating a weightless masterpiece that feels like a second skin.",
  specs: {
    Material: "100% Fine Cotton",
    Occasion: "Festive / Bridal Wear",
    Technique: "Hand-loomed Jamdani",
    Origin: "Kolkata Atelier",
  },
  images: [
    {
      src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBiXS87mkcJhL1MUncFUB8n3pdR2lFT3G2C0cSygKDndAMPXH4Y3Uoku1DsZ31S1aZ0OcyPHbMmhZS0j3zd5EnrJlQLKqO8Nkqr3AviHGnd00HsoPTOUAy8o1JJNfpmNOdkpno5UxjfZHSDXwnhe4CU9smt95AlbaSA5mYrPSfP77OK0fsnxkfU19m017Hj94w1g6wMK-L2gBxFc4-M7ej5oGL0VM4viUf1l6qv9VHweNpkAnUiLoTeNbLWwzWdli7W1ZQqBzOgJ4rR",
      alt: "Stunning cinematic shot of a deep blue handwoven Jamdani saree",
    },
    {
      src: "https://lh3.googleusercontent.com/aida-public/AB6AXuAtxIiLCbmJm4owmVkbUSbwNZNLB548WCd69cZRLowurXsY2rAY0LCehl9DWM2kfAUsDxHYnInMeBAdGiK7zzGHFh80tFOpfrX8bP-uGEob7Qla5ZGO2tEI1JA2tbv9yFX2Gly4wA8ENduOifu-buM0o0SdJkLq9e5UAcNtPM8ZJj99Ogxga_zCjajAzcuvByIXXWHy0YU_9dRYr5O_67F9_ZvIqTqMfbYu1IEllwD8inBgRu91aKzbdaNPtoXydxFZn1baK6kTK_yG",
      alt: "Extreme close-up of intricate hand-loomed Jamdani weave patterns",
    },
    {
      src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDVH7HaUyQYubmYf-aKOpBy7yngbNOAGUV3b16lWTldvUxLqcTMQ3Hybr5QgwEbPUl3crna-InUdqGUV3b16lWTldvUxLqcTMQ3Hybr5QgwEbPUl3crna",
      alt: "Artistic side view of a saree pallu",
    },
  ],
  relatedProducts: [
    {
      id: 10,
      name: "Classic Crimson Silk",
      category: "Traditional Garad",
      price: "₹ 18,900",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDLzrBVh51YPtmb5m0egACJlatq2fNzV_XLZG3TnFslCoKB4CIDOjkGKtTq2vP9ap2Qpr1N6FgUpBdgJQq3VWTZImHLKHJnYCpdfNBb0RgMBOvVW75H9rvXr8CXF69N46kdjNs-6LdOrKoUSv9Gpn4KqqxEu1Q-YBE6QUBWyIIfsJuNyfAU3gqceNwY_Q0QlEp3-xIu4EE7rObS2JErHKLyCYlT1EcS5F27ZQKL3uoVD1rAErBZ1rEgZ_EZ8FKmCh0N7aONaZ3CVo1_",
      alt: "Portrait of a woman wearing a rich crimson silk saree",
      offset: false,
    },
    {
      id: 11,
      name: "Sun-Kissed Bengal Cotton",
      category: "Everyday Luxury",
      price: "₹ 6,400",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBD_Tcjtp0jEXCkE4q2gAzErqRTjce1qhW4PpQJmuuPU8vX8novz8o5CUuId1o1kd6-8joJeD-9b5Zwn9-gC8kdAYH8HeUUV1hB6bBDyQiCI9_bEgojzisWEGsHUH8R5c9L_Ug0bq9aWiHThakszTJpVXU8ia9UaK9UNB7iq6KVGAVcB8Og5P_m-sqMrPno12QgCYe5y-rYQb3AwqKOOxAc8bmOfr-a3XZ-dTH8_GBACrFdngCuGxr_ENJZ0X5TybNov6k8HxEtn5GK",
      alt: "Vibrant marigold yellow handloom saree",
      offset: true,
    },
    {
      id: 12,
      name: "Hand-Painted Tussar",
      category: "Artisanal Story",
      price: "₹ 21,200",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCgLbZzC_w9UfSyELZ0zmVYE_QR7V6oV1bWxEd0yn5wJTA0Gm95hltWZnIg9iIFe8IDN0Lg181g0o3DAhfkUD55Zm5xHxQ50f1xpo6AMiyryTpGNN27KvBxXT56VfyKRjPCVsrMD4rHNu4R0G-wZ-z4XtE3MP6W2hAa_AhxHz-yAM3-cM-sPPQt1WkIoew7odNV7zTrDCG3s7vaZOzUh1IXMiY2dOsrbTVReGGEF9egUCaORdVw4clpEpvgKf4k1BFv7TmceVfBO05z",
      alt: "Earthy beige Tussar silk saree with tribal hand-painted motifs",
      offset: false,
    },
  ],
};
